-- =============================================================
-- KritiQ Seed Data — 002_seed.sql
-- Run after 001_schema.sql
-- Adds: users, creator, updates movie/music poster URLs
--       from Cloudinary public_ids generated by seedCloudinary.mjs
-- =============================================================

-- ─── Users ────────────────────────────────────────────────────────────────────
-- Passwords are bcrypt hashes of the plaintext shown in comments.
-- Generate fresh hashes with: htpasswd -bnBC 10 "" yourpassword | tr -d ':\n'

INSERT INTO users (id, email, username, password_hash, role, is_verified, vote_weight)
VALUES
    -- password: Admin@kritiq1
    (
        '00000000-0000-0000-0000-000000000001',
        'admin@kritiq.ng',
        'kritiq_admin',
        '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
        'admin',
        TRUE,
        1.0
    ),
    -- password: Creator@kritiq1
    (
        '00000000-0000-0000-0000-000000000002',
        'creator@kritiq.ng',
        'kritiq_creator',
        '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
        'creator',
        TRUE,
        1.5
    ),
    -- password: User@kritiq1
    (
        '00000000-0000-0000-0000-000000000003',
        'user@kritiq.ng',
        'kritiq_user',
        '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
        'user',
        TRUE,
        1.0
    )
     ('00000000-0000-0000-0000-000000000005',
     'critic@kritiq.ng', 
     'kritiq_critic', 
     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
     'critic',
     TRUE,
     2.0)
ON CONFLICT (email) DO NOTHING;

-- ─── Creator Profile ──────────────────────────────────────────────────────────

INSERT INTO creators (id, user_id, company_name, bio, tier, is_verified, website_url, social_handle)
VALUES (
    '00000000-0000-0000-0000-000000000010',
    '00000000-0000-0000-0000-000000000002',
    'KritiQ Demo Studio',
    'Demo creator account for KritiQ platform development and testing.',
    'pro',
    TRUE,
    'https://kritiq.ng',
    '@kritiq_ng'
)
ON CONFLICT (user_id) DO NOTHING;

-- ─── Movie Poster URLs ────────────────────────────────────────────────────────
-- public_id format: kritiq/uploads/images/posters/<slug>
-- The poster_url stored here is the Cloudinary public_id (not the full URL).
-- The frontend resolves the full CDN URL via getPosterUrl() in urlBuilders.js.

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/amina',
    is_featured = TRUE
WHERE slug = 'amina' OR title ILIKE '%amina%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/ayinla'
WHERE slug = 'ayinla' OR title ILIKE '%ayinla%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/blackout'
WHERE slug = 'blackout' OR title ILIKE '%blackout%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/king-of-boys'
WHERE slug ILIKE '%king-of-boys%' OR title ILIKE '%king of boys%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/king-of-thieves'
WHERE slug ILIKE '%king-of-thieves%' OR title ILIKE '%king of thieves%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/the-arbitration'
WHERE slug ILIKE '%arbitration%' OR title ILIKE '%arbitration%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/the-ghost-and-the-tout'
WHERE slug ILIKE '%ghost-and-the-tout%' OR title ILIKE '%ghost and the tout%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/the-grudge'
WHERE slug ILIKE '%grudge%' OR title ILIKE '%the grudge%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/funmilayo-ransome-kuti'
WHERE slug ILIKE '%funmilayo%' OR title ILIKE '%funmilayo%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/house-of-ga-a'
WHERE slug ILIKE '%ga%a%' OR title ILIKE '%ga''a%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/dead-tide'
WHERE slug ILIKE '%dead-tide%' OR title ILIKE '%dead tide%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/stalker'
WHERE slug = 'stalker' OR title ILIKE '%stalker%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/last-flight-to-abuja'
WHERE slug ILIKE '%last-flight%' OR title ILIKE '%last flight%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/love-at-a-cost'
WHERE slug ILIKE '%love-at-a-cost%' OR title ILIKE '%love at a cost%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/love-in-every-word'
WHERE slug ILIKE '%love-in-every-word%' OR title ILIKE '%love in every word%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/my-father-s-shadow'
WHERE slug ILIKE '%father%shadow%' OR title ILIKE '%father%shadow%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/once-upon-a-street-girl'
WHERE slug ILIKE '%street-girl%' OR title ILIKE '%street girl%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/avery-dirty-christmas'
WHERE slug ILIKE '%dirty-christmas%' OR title ILIKE '%dirty christmas%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/baby-police'
WHERE slug ILIKE '%baby-police%' OR title ILIKE '%baby police%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/behind-the-scenes'
WHERE slug ILIKE '%behind-the-scenes%' OR title ILIKE '%behind the scenes%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/heart-lock'
WHERE slug ILIKE '%heart%lock%' OR title ILIKE '%heart%lock%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/three-cold-dishes'
WHERE slug ILIKE '%three-cold%' OR title ILIKE '%three cold%';

UPDATE movies SET
    poster_url = 'kritiq/uploads/images/posters/ti-oluwa-ni-ile'
WHERE slug ILIKE '%ti-oluwa%' OR title ILIKE '%ti oluwa%';

-- ─── Insert any seeded movies not yet in the table ────────────────────────────
-- (schema seed only added 5; the remaining come from your poster files)

INSERT INTO movies (title, slug, description, release_date, status, genre, poster_url, is_featured)
VALUES
    ('Amina',               'amina',                'The story of Queen Amina of Zazzau.',                      '2021-09-10', 'released',    'Historical/Action', 'kritiq/uploads/images/posters/amina',               TRUE),
    ('Ayinla',              'ayinla',               'A biopic on legendary Sakara musician Ayinla Omowura.',    '2021-05-28', 'released',    'Drama/Biography',   'kritiq/uploads/images/posters/ayinla',              FALSE),
    ('Baby Police',         'baby-police',          'A comedy about kids who take policing into their hands.',  '2022-01-01', 'released',    'Comedy',            'kritiq/uploads/images/posters/baby-police',         FALSE),
    ('Behind The Scenes',   'behind-the-scenes',    'The untold story of what happens off-camera.',             '2023-03-17', 'released',    'Drama',             'kritiq/uploads/images/posters/behind-the-scenes',   FALSE),
    ('Blackout',            'blackout',             'A city-wide power cut turns into a night of chaos.',       '2022-11-04', 'released',    'Thriller',          'kritiq/uploads/images/posters/blackout',            FALSE),
    ('Dead Tide',           'dead-tide',            'Fishermen off the Lagos coast encounter the unknown.',     '2023-07-21', 'released',    'Horror',            'kritiq/uploads/images/posters/dead-tide',           FALSE),
    ('Funmilayo Ransome-Kuti','funmilayo-ransome-kuti','The life of Nigeria''s foremost female activist.',      '2023-10-20', 'released',    'Biographical',      'kritiq/uploads/images/posters/funmilayo-ransome-kuti',FALSE),
    ('Heart & Lock',        'heart-and-lock',       'Two strangers. One safe. A lifetime of secrets.',         '2024-02-14', 'released',    'Romance/Thriller',  'kritiq/uploads/images/posters/heart-lock',          FALSE),
    ('House of Ga''a',      'house-of-ga-a',        'Epic tale of the infamous Oyo Empire warlord.',           '2023-04-07', 'released',    'Historical/Drama',  'kritiq/uploads/images/posters/house-of-ga-a',       TRUE),
    ('King Of Boys',        'king-of-boys',         'The ruthless rise of Alhaja Eniola Salami.',              '2019-10-04', 'released',    'Crime/Drama',       'kritiq/uploads/images/posters/king-of-boys',        TRUE),
    ('King Of Thieves',     'king-of-thieves',      'Based on the real-life Osodi Robbery of 1995.',           '2022-09-23', 'released',    'Crime/Action',      'kritiq/uploads/images/posters/king-of-thieves',     FALSE),
    ('Last Flight To Abuja','last-flight-to-abuja', 'A plane. A storm. Passengers with secrets.',              '2012-11-02', 'released',    'Thriller',          'kritiq/uploads/images/posters/last-flight-to-abuja',FALSE),
    ('Love At A Cost',      'love-at-a-cost',       'Love is never free — someone always pays.',               '2024-04-05', 'released',    'Romance/Drama',     'kritiq/uploads/images/posters/love-at-a-cost',      FALSE),
    ('Love In Every Word',  'love-in-every-word',   'A novelist falls for the subject of her next book.',      '2024-06-21', 'released',    'Romance',           'kritiq/uploads/images/posters/love-in-every-word',  FALSE),
    ('My Father''s Shadow', 'my-fathers-shadow',    'A son reckons with the legend — and sins — of his father.','2023-08-18','released',    'Drama',             'kritiq/uploads/images/posters/my-father-s-shadow',  FALSE),
    ('Once Upon A Street Girl','once-upon-a-street-girl','A girl from the streets fights for a different life.','2022-05-13','released',    'Drama',             'kritiq/uploads/images/posters/once-upon-a-street-girl',FALSE),
    ('Stalker',             'stalker',              'She thought she was safe. She was wrong.',                 '2023-09-29', 'released',    'Thriller/Horror',   'kritiq/uploads/images/posters/stalker',             FALSE),
    ('The Arbitration',     'the-arbitration',      'A sexual harassment case that splits a corporation.',     '2016-11-11', 'released',    'Legal/Drama',       'kritiq/uploads/images/posters/the-arbitration',     FALSE),
    ('The Ghost And The Tout','the-ghost-and-the-tout','A ghost and a street tout team up to survive Lagos.',  '2018-10-26', 'released',    'Comedy/Fantasy',    'kritiq/uploads/images/posters/the-ghost-and-the-tout',FALSE),
    ('The Grudge',          'the-grudge-ng',        'A family feud that spans three generations.',             '2024-03-08', 'released',    'Drama',             'kritiq/uploads/images/posters/the-grudge',          FALSE),
    ('Three Cold Dishes',   'three-cold-dishes',    'A Chinese-Nigerian love story set in Lagos.',             '2023-12-01', 'released',    'Romance/Drama',     'kritiq/uploads/images/posters/three-cold-dishes',   FALSE),
    ('Ti Oluwa Ni Ile',     'ti-oluwa-ni-ile',      'The land belongs to God — but men will kill for it.',     '2022-07-15', 'released',    'Drama',             'kritiq/uploads/images/posters/ti-oluwa-ni-ile',     FALSE),
    ('A Very Dirty Christmas','a-very-dirty-christmas','Lagos. December. Nothing goes as planned.',            '2023-12-22', 'released',    'Comedy',            'kritiq/uploads/images/posters/avery-dirty-christmas',FALSE)
ON CONFLICT (slug) DO UPDATE SET
    poster_url  = EXCLUDED.poster_url,
    description = COALESCE(EXCLUDED.description, movies.description),
    genre       = COALESCE(EXCLUDED.genre, movies.genre);

-- ─── Music Cover URLs ─────────────────────────────────────────────────────────

INSERT INTO music (title, slug, artist, description, release_date, status, genre, label, cover_url, is_featured, hype_score, total_hype_votes, total_likes)
VALUES
    ('Fere',                        'beautiful-nubia-fere',                  'Beautiful Nubia',                   'Roots and culture from the master of Yoruba folk.',              '2018-03-01', 'released', 'Folk/Roots',  'Roots Renaissance',  'kritiq/uploads/images/posters/beautiful-nubia-fere',                  FALSE, 0, 0, 0),
    ('Mr Boombastic',               'blaqbonez-mr-boombastic',               'Blaqbonez',                         'The self-proclaimed best rapper brings heat.',                   '2022-06-10', 'released', 'Hip-Hop',     'Chocolate City',     'kritiq/uploads/images/posters/blaqbonez-mr-boombastic',               TRUE,  0, 0, 0),
    ('Make E No Cause Fight II',    'boj-falz-ajebutter22-make-e-no-cause-fight-ii', 'BOJ x Falz x AjeButter22', 'The long-awaited sequel to the fan favourite collab.',           '2023-04-14', 'released', 'Afrofusion',  'Independent',        'kritiq/uploads/images/posters/boj-x-falz-x-ajebutter22-make-e-no-cause-fight-ii', TRUE, 0, 0, 0),
    ('A Good Time',                 'davido-a-good-time',                    'Davido',                            'The album that solidified Davido''s global Afrobeats dominance.','2019-11-22', 'released', 'Afrobeats',   'DMW/Epic',           'kritiq/uploads/images/posters/davido-a-good-time',                    TRUE,  0, 0, 0),
    ('No More War',                 'oliver-de-coque-no-more-war',           'King (Dr) Oliver De Coque',         'A classic from the highlife guitar legend.',                     '1985-01-01', 'released', 'Highlife',    'Ogene Sound',        'kritiq/uploads/images/posters/king-dr-oliver-de-coque-no-more-war',   FALSE, 0, 0, 0),
    ('E Kilo F''omo Ode',           'king-sunny-ade-e-kilo-f-omo-ode',       'King Sunny Ade',                    'Juju royalty. Timeless groove from the Baba Aruwa.',             '1978-01-01', 'released', 'Juju',        'African Songs',      'kritiq/uploads/images/posters/king-sunny-ade-e-kilo-f-omo-ode',       FALSE, 0, 0, 0),
    ('The Road To Ubatuba',         'peter-king-the-road-to-ubatuba',        'Peter King',                        'A jazz-meets-Afrobeat masterwork rediscovered.',                 '1974-01-01', 'released', 'Jazz/Afrobeat','EMI Nigeria',        'kritiq/uploads/images/posters/peter-king-the-road-to-ubatuba',        FALSE, 0, 0, 0),
    ('The Palmwine Express',        'sdc-the-palmwine-express',              'SDC',                               'Palmwine music for the digital generation.',                     '2021-08-20', 'released', 'Palmwine',    'Independent',        'kritiq/uploads/images/posters/sdc-the-palmwine-express',              FALSE, 0, 0, 0),
    ('Try Me',                      'tems-try-me',                           'Tems',                              'The breakout single that announced Tems to the world.',          '2020-07-23', 'released', 'Afro-soul',   'Since ''93',         'kritiq/uploads/images/posters/tems-try-me',                           TRUE,  0, 0, 0),
    ('49-99',                       'tiwa-savage-49-99',                     'Tiwa Savage',                       'A political anthem wrapped in undeniable groove.',               '2019-09-27', 'released', 'Afropop',     'Universal Music',    'kritiq/uploads/images/posters/tiwa-savage-49-99',                     TRUE,  0, 0, 0),
    ('Love Is Contagious',          'wurld-love-is-contagious',              'Wurld',                             'The R&B album that proved Nigeria had its own.',                 '2019-11-15', 'released', 'R&B',         'Hennessy Artistry',  'kritiq/uploads/images/posters/wurld-love-is-contagious',              FALSE, 0, 0, 0)
ON CONFLICT (slug) DO UPDATE SET
    cover_url   = EXCLUDED.cover_url,
    description = COALESCE(EXCLUDED.description, music.description),
    genre       = COALESCE(EXCLUDED.genre, music.genre);

-- ─── Feature flags — mark hero content ────────────────────────────────────────

UPDATE movies SET is_featured = TRUE
WHERE slug IN (
    'king-of-boys',
    'house-of-ga-a',
    'amina',
    'a-tribe-called-judah-2',
    'gangs-of-lagos-2'
);

UPDATE music SET is_featured = TRUE
WHERE slug IN (
    'tems-try-me',
    'tiwa-savage-49-99',
    'davido-a-good-time',
    'blaqbonez-mr-boombastic',
    'boj-falz-ajebutter22-make-e-no-cause-fight-ii'
);